- hosts: servers
  tasks:
    - import_tasks: ./tasks/base.yml
  roles:
#    - role: gantsign.oh-my-zsh
#      users:
#        - username: "{{ ansible_user_id }}"
#          oh_my_zsh:
#            plugins:
#              - git
#              - gradle
#              - mvn
    - role: brianhartsock.prezto
#    - role: willshersystems.sshd
#      become: true
#    - role: geerlingguy.docker
#      become: true
#      docker_users:
#        - "{{ ansible_user_id }}"
#    - role: andrewrothstein.podman
#      become: true
    - role: geerlingguy.nodejs
      become: true
      vars:
        nodejs_version: "16.x"
    - role: ocha.yarn
      become: true
    - role: comcast.sdkman
      become: true
      sdkman_user: "{{ ansible_user_id }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 17.0.1-open }
