images:
- location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.img"
  arch: "aarch64"
mounts:
- location: "~"
  writable: true
- location: "/tmp/lima"
  writable: true
containerd:
  system: false
  user: false
provision:
- mode: system
  script: |
    #!/bin/bash
    apt-get update
    apt-get install -y direnv build-essential zip unzip
- mode: user
  script: |
    #!/bin/bash
    echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
    curl -s "https://get.sdkman.io" | bash
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    #source ~/.bashrc
    #nvm install --lts
    #npm install --global yarn
    #sdk install java 17.0.1-open
